Repository Myongji-Graduate/MyongjiGraduate-BE, pull requests merged in 2022-10, with the labels that each got.

#24 Codecov gitaction script 수정
  .github/workflows/pr-test.yml
Labels: 공통

#30 졸업 요건 조회 api 응답 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/dto/BasicInfo.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/dto/GraduationResult.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/dto/Transcript.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/entity/GraduationRequirement.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/service/DefaultGraduationService.java
Labels: 리팩토링

#35 api controller 응답 타입 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/controller/GraduationApiController.java
Labels: 공통

#36 환경 변수명 수정
  .github/workflows/pr-test.yml
  .github/workflows/sonarqube.yml
Labels: 버그 수정

#37 gitaction cicd setting
  .github/workflows/deploy.yml
  appsepc.yml
  build.gradle
  scripts/deploy.sh
Labels: 공통

#38 [#34]fix: s3 버킷 이름 수정
  .github/workflows/deploy.yml
Labels: 버그 수정

#39 codedeploy appspec 파일명 오타 수정
  appspec.yml
Labels: 버그 수정

#40 code deploy user 변경
  appspec.yml
Labels: 버그 수정

#41 deploy script 파일 directory 수정
  scripts/deploy.sh
Labels: 버그 수정

#44 수강과목정보 중복항목 값 처리 로직 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/service/DefaultGraduationService.java
Labels: 버그 수정

#48 프로젝트 스프린트 종료에 따른 리드미 업데이트
  readme.md
Labels: 문서

#50 영어 기준 점수 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/dto/EnglishLevel.java
Labels: 버그 수정
