Repository Myongji-Graduate/MyongjiGraduate-BE, pull requests merged in 2022-11, with the labels that each got.

#63 [#62]feat: 과목 엔티티 중복과목코드 컬럼 추가
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/dto/EnglishLevel.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/service/DefaultGraduationService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/entity/Lecture.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/entity/LectureCode.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/entity/LectureCodeConverter.java
Labels: 기능

#75 [#52]chore: jwt secret 수정
  src/main/resources/application.yml
Labels: 공통

#77 [#76]feat: 토큰 검증용 api 추가
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/controller/AuthController.java
Labels: 기능

#91 [#86]refactor: AuthenticatedUser 필드 타입 변경
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/dto/AuthenticatedUser.java
Labels: 리팩토링

#94 [#84]fix: 유저 인증처리 쿼리 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/user/repository/UserRepository.java
Labels: 버그 수정

#97 [#61]feat: 과목 검색 결과 폐강 여부 추가
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/dto/SearchedLecture.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/repository/LectureCustomRepositoryImpl.java
Labels: 기능

#102 일반 교양 과목이 존재 할 경우 수강과목에서 제외 처리
  src/main/java/com/plzgraduate/myongjigraduatebe/user/service/DefaultTakenLectureService.java
Labels: 리팩토링

#104 영어 레벨 표기 및 전달 방식 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/dto/SignUpRequest.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/entity/EnglishLevel.java
  src/test/java/com/plzgraduate/myongjigraduatebe/common/MockUserIsInitializedSecurityContextFactory.java
  src/test/java/com/plzgraduate/myongjigraduatebe/common/MockUserNotIsInitializedSecurityContextFactory.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/controller/UserControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/service/DefaultUserServiceTest.java
Labels: 리팩토링

#107 fix: 졸업 요건 검사 총 학점 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/entity/GraduationRequirement.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/service/DefaultGraduationService.java
Labels: 버그 수정

#108 상세 카테고리 결과 충족여부 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/dto/DetailCategoryResult.java
Labels: 버그 수정

#110 초기화 및 토큰 검증 기능 추가
  src/main/java/com/plzgraduate/myongjigraduatebe/common/config/SecurityConfig.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/controller/UserController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/dto/UserInitCheckResponse.java
Labels: 기능

#111 test: checkInit 메소드 테스트 추가
  src/test/java/com/plzgraduate/myongjigraduatebe/user/controller/UserControllerTest.java
Labels: 테스트

#113 중복 체크 로직 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/service/DefaultGraduationService.java
Labels: 버그 수정

#114 중복코드 관련 과목 조회 쿼리 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/service/DefaultGraduationService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/repository/LectureRepository.java
Labels: 버그 수정

#115 미 이수 과목 정보 폐지 필터처리
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/service/DefaultGraduationService.java
Labels: 리팩토링

#118 [#89]fix: 대체코드 과목 미존재 예외 처리
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/service/DefaultGraduationService.java
Labels: 버그 수정

#122 파싱된 텍스트 기록 추가
  src/main/java/com/plzgraduate/myongjigraduatebe/user/controller/UserController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/entity/ParsingResult.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/entity/RecodeParsingText.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/repository/RecodeParsingTextRepository.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/controller/UserControllerTest.java
Labels: 기능

#126 [#125]feat: 전공선택필수 초과 과목 이관 기능 구현
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/dto/DetailCategoryResult.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/dto/DetailGraduationResult.java
Labels: 버그 수정, 기능

#129 [#125]fix: 전공선택필수 초과 과목 이관 기능 누락 학과 추가
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/dto/DetailGraduationResult.java
Labels: 버그 수정

#130 파일 입력 관련 에러 메세지 출력 리팩토링
  src/main/java/com/plzgraduate/myongjigraduatebe/common/exception/ExceptionController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/controller/UserController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/dto/ParsingTextDto.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/service/DefaultTakenLectureService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/service/DefaultUserService.java
Labels: 리팩토링
