Repository Myongji-Graduate/MyongjiGraduate-BE, pull requests merged in 2023-12, with the labels that each got.

#199 cd git actions 작성
  .github/workflows/deploy-dev.yml
  .github/workflows/pr-test.yml
  .github/workflows/sonarqube.yml
  .gitignore
  Dockerfile
  gradlew
  infra/localcontainer/docker-compose.yml
  infra/localcontainer/remove.sh
  infra/localcontainer/start.sh
  infra/localcontainer/stop.sh
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/adaptor/out/persistence/RefreshTokenAdaptor.java
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/adaptor/out/persistence/RefreshTokenRedisEntity.java
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/adaptor/out/persistence/RefreshTokenRepository.java
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/application/service/token/RefreshTokenService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/core/EnvironmentCheck.java
  src/main/java/com/plzgraduate/myongjigraduatebe/core/HealthCheckController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/core/config/RedisConfig.java
  src/main/java/com/plzgraduate/myongjigraduatebe/core/config/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: 🔧 chore, size/L

#208 fix: 비밀번호 정규표현식 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/adaptor/in/web/signin/SignInRequest.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/signup/SignUpRequest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/auth/adaptor/in/web/signin/SignInControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/signup/SignUpControllerTest.java
Labels: 🐛 fix, size/M

#212 refactor: modify user api endpoint
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/finduserinformation/FindUserInformationController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/withdraw/WithDrawController.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/finduserinformation/FindUserInformationControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/withdraw/WithDrawControllerTest.java
Labels: ♻️ refactor, size/XS

#213 refactor: 규칙 수정에 따른 비밀번호 재설정 API 변경
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/resetpassword/ResetPasswordRequest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/resetpassword/ResetPasswordControllerTest.java
Labels: ♻️ refactor, size/S

#215 refactor: 로그인 폼 형식 오류 401 UnAuthorized 통일
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/adaptor/in/web/signin/SignInRequest.java
  src/main/java/com/plzgraduate/myongjigraduatebe/core/exception/GlobalExceptionHandler.java
  src/main/java/com/plzgraduate/myongjigraduatebe/core/exception/UnAuthorizedException.java
  src/test/java/com/plzgraduate/myongjigraduatebe/auth/adaptor/in/web/signin/SignInControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/auth/adaptor/in/web/token/TokenControllerTest.java
Labels: ♻️ refactor, size/M

#217 refactor: 회원 탈퇴 api password validation 추가
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/withdraw/WithDrawController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/withdraw/WithDrawRequest.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/withdraw/WithDrawCommand.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/withdraw/WithDrawUserUseCase.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/withdraw/WithDrawUserService.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/withdraw/WithDrawControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/application/service/withdraw/WithDrawUserServiceTest.java
Labels: ♻️ refactor, size/L

#218 refactor: cd 도커 명령어 변경
  .github/workflows/deploy-dev.yml
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/application/service/ParsingTextHistoryService.java
Labels: ♻️ refactor, size/XS

#219 fix: 행정학과, 경영정보학과 전공선택필수 과목 추가
  .github/workflows/deploy-dev.yml
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/MajorManager.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/exception/OptionalMandatory.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/exception/OptionalMandatoryHandler.java
Labels: 🐛 fix, size/M

#223 test: 전과생 parsing 데이터 입력 정보 확인
  src/test/java/com/plzgraduate/myongjigraduatebe/parsing/domain/ParsingInformationTest.java
Labels: size/S

#224 v2에 따른 readme 업데이트
  readme.md
Labels: 📝 docs, size/M

#227 기존 deploy.yml 과 스크립트 삭제
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy.yml
  .github/workflows/pr-test.yml
  appspec.yml
  codecov.yml
  spy.log
Labels: 🔧 chore, size/L

#228 서비스 대상자가 아닐 경우 에러 반환
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/application/service/ParsingTextService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/signup/SignUpService.java
Labels: 🐛 fix, size/S
