Repository Myongji-Graduate/MyongjiGraduate-BE, pull requests merged in 2023-09, with the labels that each got.

#170 PDF 파싱 처리 로직 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/adaptor/in/web/SignInController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/jwt/TokenAuthenticationFilter.java
  src/main/java/com/plzgraduate/myongjigraduatebe/core/exception/GlobalExceptionHandler.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/adapter/out/LectureJpaEntity.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/adapter/out/LectureMapper.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/adapter/out/LecturePersistenceAdaptor.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/adapter/out/LectureRepository.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/application/port/out/LoadLecturePort.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/domain/model/Lecture.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/adaptor/in/web/ParsingTextController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/adaptor/in/web/ParsingTextRequest.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/adaptor/out/ParsingTextHistoryAdaptor.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/adaptor/out/ParsingTextHistoryJpaEntity.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/adaptor/out/ParsingTextHistoryMapper.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/adaptor/out/ParsingTextRepository.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/application/port/in/ParsingTextUseCase.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/application/port/in/command/ParsingTextCommand.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/application/port/out/SaveParsingTextHistoryPort.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/application/service/InvalidPdfException.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/application/service/ParsingTextService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/application/service/PdfParsingException.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/domain/ParsingInformation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/domain/ParsingResult.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/domain/ParsingStudentCategoryDto.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/domain/ParsingTakenLectureDto.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/domain/ParsingTextHistory.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/adaptor/out/TakenLectureJpaEntity.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/adaptor/out/TakenLectureMapper.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/adaptor/out/TakenLecturePersistenceAdaptor.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/adaptor/out/TakenLectureRepository.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/application/port/out/DeleteTakenLecturePort.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/application/port/out/SaveTakenLecturePort.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/domain/model/TakenLecture.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/out/persistence/UserJpaEntity.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/out/persistence/UserPersistenceAdaptor.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/out/LoadUserPort.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/domain/model/StudentCategory.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/domain/model/User.java
  src/test/java/com/plzgraduate/myongjigraduatebe/parsing/adaptor/in/web/ParsingTextControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/parsing/adaptor/out/ParsingTextHistoryAdaptorTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/parsing/adaptor/out/ParsingTextHistoryMapperTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/parsing/application/service/ParsingTextServiceTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/parsing/domain/ParsingInformationTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/parsing/domain/ParsingTextHistoryTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/takenlecture/adaptor/out/TakenLectureMapperTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/takenlecture/adaptor/out/TakenLecturePersistenceAdaptorTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/out/persistence/UserMapperTest.java
Labels: ✨ feat, ♻️ refactor

#175 과목 검색 기능 구현
  src/main/java/com/plzgraduate/myongjigraduatebe/core/exception/GlobalExceptionHandler.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/adapter/in/web/SearchLectureController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/adapter/out/LectureJpaEntity.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/adapter/out/LecturePersistenceAdaptor.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/adapter/out/LectureQueryRepository.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/application/port/in/find/FindLecturesByIdUseCase.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/application/port/in/find/FindLecturesByLectureCodeUseCase.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/application/port/in/search/LectureResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/application/port/in/search/SearchLectureCommand.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/application/port/in/search/SearchLectureResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/application/port/in/search/SearchLectureUseCase.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/application/port/out/SearchLecturePort.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/application/service/find/FindLecturesByIdService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/application/service/find/FindLecturesByLectureCodeService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/application/service/search/SearchLectureService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/application/service/save/SaveTakenLectureFromParsingTextService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/application/service/update/UpdateTakenLectureService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/domain/model/User.java
  src/main/resources/application.yml
  src/test/java/com/plzgraduate/myongjigraduatebe/lecture/adapter/in/web/SearchLectureControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/lecture/adapter/out/LecturePersistenceAdaptorTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/lecture/adapter/out/LectureQueryRepositoryTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/lecture/adapter/out/TestQuerydslConfig.java
  src/test/java/com/plzgraduate/myongjigraduatebe/lecture/application/service/find/FindLecturesByIdServiceTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/lecture/application/service/find/FindLecturesByLectureCodeServiceTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/lecture/application/service/search/SearchLectureServiceTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/parsing/adaptor/in/web/ParsingTextControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/support/PersistenceTestSupport.java
  src/test/java/com/plzgraduate/myongjigraduatebe/support/WithMockAuthenticationUser.java
  src/test/java/com/plzgraduate/myongjigraduatebe/support/WithMockAuthenticationUserSecurityContext.java
  src/test/java/com/plzgraduate/myongjigraduatebe/takenlecture/adaptor/in/web/find/FindTakenLectureControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/takenlecture/adaptor/in/web/update/UpdateTakenLectureControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/takenlecture/application/service/save/SaveTakenLectureFromParsingTextServiceTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/takenlecture/application/service/update/UpdateTakenLectureServiceTest.java
  src/test/resources/application-test.yml
Labels: ✨ feat, ♻️ refactor

#180 아이디 찾기
  src/main/java/com/plzgraduate/myongjigraduatebe/core/config/SecurityConfig.java
  src/main/java/com/plzgraduate/myongjigraduatebe/core/exception/GlobalExceptionHandler.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/findauthid/FindAuthIdController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/out/persistence/UserPersistenceAdaptor.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/out/persistence/UserRepository.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/find/FindUserAuthIdUseCase.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/find/UserAuthIdResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/out/FindUserPort.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/find/FindUserAuthIdService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/domain/model/User.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/findauthid/FindAuthIdControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/out/persistence/UserPersistenceAdaptorTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/out/persistence/UserRepositoryTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/application/service/find/FindUserAuthIdServiceTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/domain/model/UserTest.java
Labels: ✨ feat, ♻️ refactor, size/L

#178 hotfix: 과목 데이터 존재하지 않을 경우 에러 메세지 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/user/service/DefaultTakenLectureService.java
Labels: ♻️ refactor, size/XS

#182 비밀번호 재설정
  src/main/java/com/plzgraduate/myongjigraduatebe/core/config/SecurityConfig.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/findauthid/FindAuthIdController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/resetpassword/ResetPasswordController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/resetpassword/ResetPasswordRequest.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/find/FindUserUseCase.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/resetpassword/ResetPasswordCommand.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/resetpassword/ResetPasswordUseCase.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/find/FindUserAuthIdService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/find/FindUserService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/resetpassword/ResetPasswordService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/domain/model/User.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/findauthid/FindAuthIdControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/resetpassword/ResetPasswordControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/application/service/find/FindUserAuthIdServiceTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/application/service/find/FindUserServiceTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/application/service/resetpassword/ResetPasswordServiceTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/domain/model/UserTest.java
Labels: ✨ feat, ♻️ refactor, size/L

#184 아이디 중복 체크
  src/main/java/com/plzgraduate/myongjigraduatebe/core/config/SecurityConfig.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/signup/SignUpController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/signup/SignUpRequest.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/check/AuthIdDuplicationResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/check/CheckAuthIdDuplicationUseCase.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/check/CheckAuthIdDuplicationService.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/signup/SignUpControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/application/service/check/CheckAuthIdDuplicationServiceTest.java
Labels: ✨ feat, ♻️ refactor, size/L

#186 비밀번호 재설정 - 유저 검증
  src/main/java/com/plzgraduate/myongjigraduatebe/core/config/SecurityConfig.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/resetpassword/ResetPasswordController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/validate/ValidateUserResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/validate/ValidateUserUseCase.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/validate/ValidateUserService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/domain/model/User.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/resetpassword/ResetPasswordControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/application/service/validate/ValidateUserServiceTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/domain/model/UserTest.java
Labels: ✨ feat, ♻️ refactor, size/L

#189 테스트 깨짐 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/core/config/SecurityConfig.java
  src/test/java/com/plzgraduate/myongjigraduatebe/support/WithMockAuthenticationUserSecurityContext.java
Labels: 🐛 fix, size/XS

#193 학생 정보 조회
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/finduserinformation/FindUserInformationController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/find/FindUserInformationUseCase.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/find/UserInformationResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/find/FindUserInformationService.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/finduserinformation/FindUserInformationControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/application/service/find/FindUserInformationServiceTest.java
Labels: ✨ feat, ♻️ refactor, size/L

#195 회원 탈퇴
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/withdraw/WithDrawController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/out/persistence/UserPersistenceAdaptor.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/withdraw/WithDrawUserUseCase.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/out/DeleteUserPort.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/check/CheckAuthIdDuplicationService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/check/CheckStudentNumberDuplicationService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/find/FindUserAuthIdService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/find/FindUserInformationService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/resetpassword/ResetPasswordService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/validate/ValidateUserService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/withdraw/WithDrawUserService.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/withdraw/WithDrawControllerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/adaptor/out/persistence/UserPersistenceAdaptorTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/application/service/withdraw/WithDrawUserServiceTest.java
Labels: ✨ feat, ♻️ refactor, size/L

#196 전체 졸업 결과 계산 - 리팩토링
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/adpater/in/web/CalculateGraduationController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/CalculateGraduationService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/CalculateGraduationUseCase.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/CheckGraduationUseCase.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/response/BasicInfoResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/response/ChapelResultResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/response/DetailGraduationCategoryResultResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/response/DetailGraduationResultResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/response/GraduationResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/response/LectureResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/response/RestResultResponse.java
  src/test/java/com/plzgraduate/myongjigraduatebe/fixture/UserFixture.java
  src/test/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/CalculateGraduationServiceTest.java
Labels: ♻️ refactor, size/M
