Repository Myongji-Graduate/MyongjiGraduate-BE, pull requests merged in 2024-12, with the labels that each got.

#289 [DEV-47] 봉사학점의 이수학점이 자유선택으로 반영되도록 수정(pr 재작성)
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/security/JwtAuthenticationProvider.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/NormalCultureGraduationResult.java
  src/test/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/FreeElectiveGraduationResultTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/NormalCultureGraduationResultTest.java
  src/test/resources/lecture.csv
Labels: ♻️ refactor, size/L, D-0

#294 [DEV-49] 편입 졸업 계산 로직 작성
  src/main/java/com/plzgraduate/myongjigraduatebe/completedcredit/api/dto/CompletedCreditResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/completedcredit/application/service/GenerateOrModifyCompletedCreditService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/completedcredit/domain/model/CompletedCredit.java
  src/main/java/com/plzgraduate/myongjigraduatebe/completedcredit/infrastructure/persistence/entity/CompletedCreditJpaEntity.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/service/CalculateGraduationService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/service/CheckGraduationRequirementService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/ChapelResult.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/DefaultGraduationRequirementType.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/DetailCategoryResult.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/FreeElectiveGraduationResult.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/GraduationCategory.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/GraduationRequirement.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/GraduationResult.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/NormalCultureGraduationResult.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/TransferGraduationRequirementType.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/basicacademicalculture/BusinessBasicAcademicalGraduationManager.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/basicacademicalculture/DefaultBasicAcademicalGraduationManager.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/basicacademicalculture/SocialScienceBasicAcademicGraduationManager.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/commonculture/CommonCultureDetailCategoryManager.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/coreculture/CoreCultureDetailCategoryManager.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/ElectiveMajorManager.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/MajorGraduationManager.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/application/service/ParsingAnonymousService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/domain/ParsingInformation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/domain/ParsingStudentCategoryDto.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/domain/model/TakenLectureInventory.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/api/finduserinformation/FindUserInformationApiPresentation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/update/UpdateStudentInformationService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/usecase/update/UpdateStudentInformationCommand.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/domain/model/StudentCategory.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/domain/model/TransferCredit.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/domain/model/User.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/infrastructure/adapter/persistence/entity/UserJpaEntity.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/infrastructure/adapter/persistence/mapper/UserMapper.java
  src/test/java/com/plzgraduate/myongjigraduatebe/completedcredit/application/service/GenerateOrModifyCompletedCreditServiceTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/completedcredit/domain/model/CompletedCreditTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/fixture/UserFixture.java
  src/test/java/com/plzgraduate/myongjigraduatebe/graduation/application/service/CalculateMajorGraduationServiceTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/FreeElectiveGraduationResultTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/GraduationResultTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/NormalCultureGraduationResultTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/TransferGraduationRequirementTypeTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/takenlecture/domain/model/TakenLectureInventoryTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/infrastructure/adapter/persistence/UserPersistenceAdapterTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/infrastructure/adapter/persistence/mapper/UserMapperTest.java
Labels: ✨ feat, size/XXL

#293 [DEV-51] 수강필요과목 목록 제거 - 현장실습
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/api/FindDetailGraduationApiPresentation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/DetailCategoryResult.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/GraduationCategory.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/ElectiveMajorManager.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/domain/model/TakenLectureInventory.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/domain/model/StudentCategory.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/infrastructure/adapter/persistence/UserPersistenceAdapterTest.java
Labels: ♻️ refactor, size/M, D-0

#297 [DEV-54] 편입 로직 수정 및 리팩토링
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/DetailCategoryResult.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/FreeElectiveGraduationResult.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/GraduationResult.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/basicacademicalculture/BusinessBasicAcademicalGraduationManager.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/ElectiveMajorManager.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/MajorGraduationManager.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/update/UpdateStudentInformationService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/domain/model/User.java
  src/test/java/com/plzgraduate/myongjigraduatebe/fixture/UserFixture.java
  src/test/java/com/plzgraduate/myongjigraduatebe/graduation/application/service/CalculateMajorGraduationServiceTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/application/service/update/UpdateStudentInformationServiceTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/domain/model/DefaultGraduationRequirementTypeTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/domain/model/UserTest.java
Labels: 🐛 fix, size/L, D-5
