Repository Myongji-Graduate/MyongjiGraduate-BE, pull requests merged in 2024-06, with the labels that each got.

#269 [DEV-33] 복수전공 학문기초교양 졸업계산 로직 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/service/CalculateGraduationService.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/model/GraduationResult.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/application/port/FindBasicAcademicalCulturePort.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/infrastructure/adapter/persistence/FindBasicAcademicalCulturePersistenceAdapter.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/infrastructure/adapter/persistence/repository/BasicAcademicalCultureRepository.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/domain/model/TakenLectureInventory.java
  src/test/java/com/plzgraduate/myongjigraduatebe/lecture/infrastructure/adapter/persistence/repository/BasicAcademicalCultureLectureRepositoryTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/takenlecture/domain/model/TakenLectureInventoryTest.java
Labels: 🐛 fix, size/L, D-0

#272 [DEV-35] 학사안내문 업데이트 반영
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/ElectiveMajorManager.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/MajorManager.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/MandatoryMajorManager.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/MandatoryMajorSpecialCaseHandler.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/MandatorySpecialCaseInformation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/OptionalMandatory.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/OptionalMandatoryMajorHandler.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/ReplaceMandatoryMajorHandler.java
  src/test/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/OptionalMandatoryMajorHandlerTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/major/exception/ReplaceMandatoryMajorHandlerTest.java
Labels: ♻️ refactor, size/L

#276 [DEV-37] Codecov 리포트 오류 수정
  .github/workflows/pr-test.yml
Labels: 🔧 chore, size/XS, D-3

#278 [DEV-38] 회원탈퇴 오류 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/completedcredit/application/port/DeleteCompletedCreditPort.java
  src/main/java/com/plzgraduate/myongjigraduatebe/completedcredit/infrastructure/persistence/DeletedCompletedCreditAdapter.java
  src/main/java/com/plzgraduate/myongjigraduatebe/completedcredit/infrastructure/persistence/repository/CompletedCreditRepository.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/service/withdraw/WithDrawUserService.java
  src/test/java/com/plzgraduate/myongjigraduatebe/completedcredit/infrastructure/persistence/repository/CompletedCreditRepositoryTest.java
  src/test/java/com/plzgraduate/myongjigraduatebe/user/application/service/withdraw/WithDrawUserServiceTest.java
Labels: 🐛 fix, size/M, D-0
