Repository Myongji-Graduate/MyongjiGraduate-BE, pull requests merged in 2024-01, with the labels that each got.

#233 refactor: Springdoc를 사용하여 Swagger UI를 통해 API Documentation 생성
  build.gradle
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/adaptor/in/web/signin/SignInApiPresentation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/adaptor/in/web/signin/SignInController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/adaptor/in/web/signin/SignInRequest.java
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/adaptor/in/web/token/TokenApiPresentation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/adaptor/in/web/token/TokenRequest.java
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/application/port/in/AccessTokenResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/application/port/in/TokenResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/core/HealthCheckController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/core/config/SecurityConfig.java
  src/main/java/com/plzgraduate/myongjigraduatebe/core/config/SwaggerConfig.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/adpater/in/web/CalculateGraduationApiPresentation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/adpater/in/web/CalculateGraduationController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/response/BasicInfoResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/response/ChapelResultResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/response/DetailGraduationCategoryResultResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/response/DetailGraduationResultResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/response/GraduationResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/response/LectureResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/application/port/in/response/RestResultResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/adapter/in/web/SearchLectureApiPresentation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/adapter/in/web/SearchLectureController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/lecture/application/port/in/search/LectureResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/adaptor/in/web/ParsingTextApiPresentation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/adaptor/in/web/ParsingTextController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/parsing/adaptor/in/web/ParsingTextRequest.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/adaptor/in/web/find/FindTakenLectureApiPresentation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/adaptor/in/web/find/FindTakenLectureController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/adaptor/in/web/update/UpdateTakenLectureApiPresentation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/adaptor/in/web/update/UpdateTakenLectureController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/adaptor/in/web/update/UpdateTakenLectureRequest.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/application/port/in/find/FindTakenLectureResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/takenlecture/application/port/in/find/TakenLectureResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/findauthid/FindAuthIdApiPresentation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/findauthid/FindAuthIdController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/finduserinformation/FindUserInformationApiPresentation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/finduserinformation/FindUserInformationController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/resetpassword/ResetPasswordApiPresentation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/resetpassword/ResetPasswordController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/resetpassword/ResetPasswordRequest.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/signup/SignUpApiPresentation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/signup/SignUpController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/signup/SignUpRequest.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/withdraw/WithDrawApiPresentation.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/withdraw/WithDrawController.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/adaptor/in/web/withdraw/WithDrawRequest.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/check/AuthIdDuplicationResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/check/StudentNumberDuplicationResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/find/UserAuthIdResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/find/UserInformationResponse.java
  src/main/java/com/plzgraduate/myongjigraduatebe/user/application/port/in/validate/ValidateUserResponse.java
  src/main/resources/application.yml
Labels: size/L

#234 refactor: TokenController의 API swagger 설정 interface를 상속받도록 변경
  src/main/java/com/plzgraduate/myongjigraduatebe/auth/adaptor/in/web/token/TokenController.java
Labels: size/XS

#232 fix: 핵심교양-문화와예술 예외사항 오류 수정
  src/main/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/coreculture/CoreCultureDetailCategoryManager.java
  src/test/java/com/plzgraduate/myongjigraduatebe/graduation/domain/service/coreculture/CoreCultureDetailCategoryManagerTest.java
Labels: 🐛 fix, size/M

#237 chore: dn-rule 워크플로우 스크립트 작성
  .github/workflows/dn-rule.yml
Labels: size/M, D-5
